import type { Game, Build } from "./types";

// ── GAMES ─────────────────────────────────────────────────────────────────────

export const SEED_GAMES: Game[] = [
  {
    key: "lotf",
    name: "Lords of the Fallen",
    icon: "⚔️",
    statMax: 75,
    endgameBudget: 155,
    softCaps: {
      END: 40,
      STR: 50,
      AGI: 50,
      RAD: 50,
      INF: 50,
      VIT: null,
      WIL: null,
    },
    mats: [
      {
        label: "Weapons",
        items: [
          "Deralium Nugget (early upgrade)",
          "Deralium Chunk (mid upgrade)",
          "Deralium Shard (late upgrade)",
          "Umbral Scouring (umbral scaling bump)",
          "Fulgrite (radiant scaling bump)",
        ],
      },
      {
        label: "Catalysts & Spells",
        items: [
          "Vestige Seeds (unlock vestiges)",
          "Saintly Quintessence (advanced holy spells)",
          "Inferno Quintessence (advanced fire spells)",
        ],
      },
      {
        label: "Consumables",
        items: [
          "Sanguinarix (HP flask, upgrades with Remembrance)",
          "Sinner's Bile (applies bleed)",
          "Harrower's Cloak (reduce enemy detection)",
        ],
      },
    ],
    weightInfo: [
      {
        label: "Light",
        range: "0–29.9%",
        note: "Maximum dodge speed, smallest i-frames",
      },
      {
        label: "Medium",
        range: "30–69.9%",
        note: "Standard roll, recommended for most builds",
      },
      { label: "Heavy", range: "70–99.9%", note: "Slow roll, tanky setups" },
      { label: "Overweight", range: "100%+", note: "No dodge, walk only" },
    ],
  },
  {
    key: "ds1",
    name: "Dark Souls",
    icon: "🔥",
    statMax: 99,
    endgameBudget: 200,
    softCaps: {
      VIT: 40,
      ATT: 50,
      END: 40,
      STR: 40,
      DEX: 40,
      RES: null,
      INT: 50,
      FTH: 50,
    },
    mats: [
      {
        label: "Titanite",
        items: [
          "Titanite Shard (standard +1→+5)",
          "Large Titanite Shard (+6→+10)",
          "Titanite Chunk (+11→+14)",
          "Titanite Slab (+15, max)",
        ],
      },
      {
        label: "Special Stones",
        items: [
          "Green Titanite Shard (lightning/magic path)",
          "Blue Titanite Chunk (magic +10 max)",
          "Red Titanite Chunk (fire +10 max)",
          "White Titanite Chunk (occult/divine)",
          "Dragon Scale (dragon weapons)",
        ],
      },
      {
        label: "Embers",
        items: [
          "Large Ember (standard → +10 ascension)",
          "Very Large Ember (+10 → +15)",
          "Enchanted Ember (magic path unlock)",
          "Divine Ember + Large Divine Ember",
          "Dark Ember (occult ascension)",
          "Large Flame Ember (chaos/fire path)",
          "Crystal Ember (crystal ascension)",
        ],
      },
    ],
    weightInfo: [
      { label: "Light", range: "0–25%", note: "Fastest roll (fast roll)" },
      { label: "Medium", range: "25–50%", note: "Medium roll" },
      { label: "Fat", range: "50–100%", note: "Fat roll / slow movement" },
      { label: "Over", range: "100%+", note: "No roll at all" },
    ],
  },
];

// ── BUILDS ────────────────────────────────────────────────────────────────────

export const SEED_BUILDS: Build[] = [
  // ── LOTF: Crimson Reaper ──────────────────────────────────────────────────
  {
    key: "crimson-reaper",
    gameKey: "lotf",
    label: "Crimson Reaper",
    sub: "Bleed STR/RAD Dual-Wield",
    icon: "🩸",
    accent: "#d64545",
    playstyle:
      "A relentless dual-wielder that stacks bleed through rapid STR-scaling slashes with Bloody Glory and Abiding Defender Swords. Radiance passives amplify status build-up while keeping you mobile at medium equip load. Focus: proc bleed every 4–6 hits, heal on proc via Blessed weapon infusion.",
    cls: "Partisan",
    caps: ["STR 50", "RAD 50", "END 40"],
    weaponReq: ["STR 18", "AGI 8", "RAD 12"],
    loadouts: [
      {
        id: "aggressive",
        label: "Aggressive",
        weaponWt: 18.4,
        endReq: 35,
        armor: "Remnant Knight set (partial)",
        pros: ["Maximum bleed pressure", "High poise"],
        cons: ["Heavier roll (medium)"],
      },
      {
        id: "mobile",
        label: "Mobile",
        weaponWt: 18.4,
        endReq: 30,
        armor: "Lightreaper Surcoat + light legs",
        pros: ["Lighter roll", "Better dodge windows"],
        cons: ["Less poise", "Lower armor"],
      },
    ],
    phases: [
      {
        name: "Early Game",
        range: "Levels 1–40",
        stats: { VIT: 15, END: 20, STR: 18, AGI: 10, RAD: 12, INF: 8 },
        sn: "Rush STR to 18 for main weapon requirement, then END to 20.",
        weapons: [
          {
            n: "Hallowed Sword",
            ap: 190,
            wt: 7.2,
            ef: "Bleed 28",
            eq: "Main Hand",
            d: "Starting STR weapon with innate bleed. Carried through early game.",
            loc: "Starting equipment (Partisan class) or Skyrest Bridge chest",
            up: "+1→+5 with Deralium Nuggets",
            tip: "Two-hand for extra STR scaling early until you meet weapon req.",
          },
        ],
        armor: [
          {
            n: "Iron Wayfarer Set",
            wt: 24.0,
            eq: "Full Set",
            d: "Solid early armor with decent physical defense.",
            loc: "Purchased from Stomund, Captain of the Fidelis at Skyrest",
            up: "N/A",
            tip: "Wear without helm if overweight. Swap helm for lighter option.",
          },
        ],
        acc: [],
        spells: [],
        dmg: {
          ps: 210,
          sp: 185,
          bs: 420,
          n: "Single-hand with Hallowed Sword. Bleed procs for ~200 bonus.",
        },
      },
      {
        name: "Core Weapon",
        range: "Levels 40–60",
        stats: { VIT: 18, END: 28, STR: 25, AGI: 12, RAD: 20, INF: 10 },
        sn: "Acquire Bloody Glory. Push STR to 25 and RAD to 20.",
        weapons: [
          {
            n: "Bloody Glory",
            ap: 285,
            wt: 9.4,
            ef: "Bleed 56",
            eq: "Main Hand",
            d: "Primary bleed sword with A-tier STR scaling and high innate bleed buildup.",
            loc: "Dropped by Spurned Progeny boss in Fief of the Chill Curse",
            up: "+3 with Deralium Chunks. Infuse Umbral for bleed amp.",
            tip: "Priority target. Rush this boss the moment you reach the area.",
          },
          {
            n: "Abiding Defender Sword",
            ap: 255,
            wt: 8.6,
            ef: "Bleed 44",
            eq: "Off Hand",
            d: "Off-hand for dual-wield setup. STR/RAD dual scaling.",
            loc: "Reward for defeating Abiding Defenders in Bramis Castle",
            up: "+3 with Deralium Chunks. Infuse Fulgrite for RAD bonus.",
            tip: "Use weapon art for poise-through burst combo.",
          },
        ],
        armor: [
          {
            n: "Remnant Knight Chestplate",
            wt: 12.0,
            eq: "Chest",
            d: "High physical resist + bleed resist passively. Great mid-piece.",
            loc: "Purchased from Stomund after defeating Pieta",
            up: "N/A",
            tip: "Mix with lighter legs/gauntlets to stay medium equip load.",
          },
        ],
        acc: [
          {
            n: "Crimson Rector Pendant",
            wt: 0.4,
            ef: "Bleed build-up +15%",
            eq: "Amulet",
            d: "Boosts bleed accumulation on all attacks.",
            loc: "Looted in Upper Calrath (umbral layer chest near burning gate)",
            up: "N/A",
            tip: "Core accessory — equip immediately.",
          },
        ],
        spells: [
          {
            n: "Blessed Weapon",
            ef: "Weapon gains Radiant element + heal on hit 5HP",
            eq: "Spell Slot",
            d: "Infuses your weapon with Radiance temporarily, adding small but consistent HP recovery.",
            loc: "Purchased from Molhu at Skyrest (requires RAD 15)",
            up: "N/A",
            tip: "Cast before each boss fight. 90-second duration is enough for most encounters.",
          },
        ],
        dmg: {
          ps: 340,
          sp: 290,
          bs: 680,
          n: "Dual-wield mode. Bleed proc deals ~250 bonus. RAD passives add ~40.",
        },
      },
      {
        name: "Key Accessories",
        range: "Levels 60–75",
        stats: { VIT: 22, END: 35, STR: 38, AGI: 14, RAD: 30, INF: 10 },
        sn: "Hunt remaining accessories. Push STR toward soft cap and RAD to 30.",
        weapons: [
          {
            n: "Bloody Glory +5",
            ap: 378,
            wt: 9.4,
            ef: "Bleed 72",
            eq: "Main Hand",
            d: "Fully upgraded main weapon.",
            loc: "Upgrade at Blacksmith Hub",
            up: "+4→+5 with Deralium Shards",
            tip: "Keep Umbral infusion for maximum bleed.",
          },
        ],
        armor: [
          {
            n: "Remnant Knight Set (partial)",
            wt: 28.0,
            eq: "Chest + Gauntlets",
            d: "Drop legs for lighter option.",
            loc: "Stomund vendor",
            up: "N/A",
            tip: "Total equip load target: under 60% of max for medium roll.",
          },
        ],
        acc: [
          {
            n: "Sinner's Ring",
            wt: 0.3,
            ef: "Status build-up +10% all",
            eq: "Ring 1",
            d: "Flat status amplifier — stacks with Crimson Rector.",
            loc: "Forsaken Fen umbral layer — behind the sunken ruins",
            up: "N/A",
            tip: "Slot 1 priority alongside Crimson Rector.",
          },
          {
            n: "Vigor Ring +1",
            wt: 0.2,
            ef: "+15% max HP",
            eq: "Ring 2",
            d: "Survivability ring for boss fights.",
            loc: "Found in Revelation Depths chest room",
            up: "N/A",
            tip: "Swap out for damage ring in farming runs.",
          },
        ],
        spells: [
          {
            n: "Holy Salvo",
            ef: "Radiant projectiles, moderate damage",
            eq: "Spell Slot 2",
            d: "Ranged Radiance option for gap opponents.",
            loc: "Purchased from Pieta's memory fragment",
            up: "N/A",
            tip: "Use to cheese distant archers and ranged enemies.",
          },
        ],
        dmg: {
          ps: 430,
          sp: 370,
          bs: 860,
          n: "Full accessory set. Bleed proc: ~290 bonus. Consistent ~720 sustained DPS.",
        },
      },
      {
        name: "Unlock Spells",
        range: "Levels 70–85",
        stats: { VIT: 25, END: 38, STR: 45, AGI: 15, RAD: 38, INF: 10 },
        sn: "RAD to 38 unlocks tier-3 Radiance spells. STR approaching soft cap.",
        weapons: [
          {
            n: "Bloody Glory +5",
            ap: 378,
            wt: 9.4,
            ef: "Bleed 72",
            eq: "Main Hand",
            d: "Same. Focus budget on stats now.",
            loc: "—",
            up: "Maxed",
            tip: "Consider Umbral Scouring for final bleed bump.",
          },
        ],
        armor: [
          {
            n: "Lightreaper Surcoat",
            wt: 9.6,
            eq: "Chest",
            d: "Lighter alternative for better mobility.",
            loc: "Reward from Lightreaper boss fight (optional)",
            up: "N/A",
            tip: "Swap to this if you find yourself getting caught in combos.",
          },
        ],
        acc: [],
        spells: [
          {
            n: "Radiant Weapon",
            ef: "Full Radiance infusion, +25% RAD dmg",
            eq: "Spell Slot 1",
            d: "Upgraded version of Blessed Weapon — larger bonus damage.",
            loc: "Purchased from Molhu at RAD 35",
            up: "N/A",
            tip: "Replaces Blessed Weapon. Much higher damage bump.",
          },
          {
            n: "Surge of Hallowed Ground",
            ef: "AoE Radiance burst, stagger",
            eq: "Spell Slot 2",
            d: "Ground-targeted AoE that staggers groups.",
            loc: "Abbey of the Hallowed Sisters secret chest",
            up: "N/A",
            tip: "Excellent against mob groups in NG+ runs.",
          },
        ],
        dmg: {
          ps: 490,
          sp: 420,
          bs: 980,
          n: "Radiant Weapon buff adds ~80 flat damage. Bleed proc: ~330.",
        },
      },
      {
        name: "Mid-to-Late",
        range: "Levels 85–105",
        stats: { VIT: 28, END: 40, STR: 50, AGI: 16, RAD: 45, INF: 10 },
        sn: "STR hits soft cap (50). END hits soft cap (40). RAD at 45.",
        weapons: [
          {
            n: "Bloody Glory +5 (Umbral)",
            ap: 415,
            wt: 9.4,
            ef: "Bleed 88",
            eq: "Main Hand",
            d: "Umbral Scouring applied — peak bleed build-up.",
            loc: "—",
            up: "Umbral Scouring from umbral vendor",
            tip: "This is the final form. No further upgrades needed.",
          },
          {
            n: "Abiding Defender Sword +5",
            ap: 360,
            wt: 8.6,
            ef: "Bleed 66",
            eq: "Off Hand",
            d: "Fully upgraded off-hand.",
            loc: "—",
            up: "Maxed + Fulgrite infusion",
            tip: "Dual-wield stance for maximum bleed pressure.",
          },
        ],
        armor: [
          {
            n: "Remnant Knight Set",
            wt: 32.0,
            eq: "Full Set",
            d: "All pieces for maximum poise in mid-late game.",
            loc: "Stomund",
            up: "N/A",
            tip: "You have enough END now to stay medium load in full set.",
          },
        ],
        acc: [
          {
            n: "Crimson Rector Pendant",
            wt: 0.4,
            ef: "Bleed +15%",
            eq: "Amulet",
            d: "Core.",
            loc: "—",
            up: "N/A",
            tip: "Never swap this out.",
          },
          {
            n: "Sinner's Ring",
            wt: 0.3,
            ef: "+10% status",
            eq: "Ring 1",
            d: "Core.",
            loc: "—",
            up: "N/A",
            tip: "Keep.",
          },
          {
            n: "Briar Ring",
            wt: 0.2,
            ef: "+8% STR scaling damage",
            eq: "Ring 2",
            d: "Replaces Vigor Ring for pure damage at this survivability level.",
            loc: "Bramis Castle treasure room",
            up: "N/A",
            tip: "Swap in for bosses once you're comfortable.",
          },
        ],
        spells: [],
        dmg: {
          ps: 580,
          sp: 490,
          bs: 1160,
          n: "At STR/RAD soft caps. Dual-wield bleed proc ~380 per trigger.",
        },
      },
      {
        name: "Endgame",
        range: "Levels 105–130",
        stats: { VIT: 35, END: 40, STR: 50, AGI: 18, RAD: 50, INF: 10 },
        sn: "RAD hits soft cap. VIT pumped for NG+ survivability. True endgame loadout.",
        weapons: [
          {
            n: "Bloody Glory +5 (Umbral)",
            ap: 415,
            wt: 9.4,
            ef: "Bleed 88",
            eq: "Main Hand",
            d: "Maxed.",
            loc: "—",
            up: "Complete",
            tip: "Swap to Fulgrite version vs. Umbral-resistant bosses.",
          },
          {
            n: "Abiding Defender Sword +5",
            ap: 360,
            wt: 8.6,
            ef: "Bleed 66",
            eq: "Off Hand",
            d: "Maxed.",
            loc: "—",
            up: "Complete",
            tip: "Off-hand for maximum bleed combo strings.",
          },
        ],
        armor: [
          {
            n: "Remnant Knight Full Set",
            wt: 32.0,
            eq: "Full Set",
            d: "Full poise setup.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        acc: [
          {
            n: "Crimson Rector Pendant",
            wt: 0.4,
            ef: "Bleed +15%",
            eq: "Amulet",
            d: "Core.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
          {
            n: "Sinner's Ring",
            wt: 0.3,
            ef: "+10% status",
            eq: "Ring 1",
            d: "Core.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
          {
            n: "Briar Ring",
            wt: 0.2,
            ef: "+8% STR scaling",
            eq: "Ring 2",
            d: "Pure damage.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        spells: [
          {
            n: "Radiant Weapon",
            ef: "+25% RAD dmg",
            eq: "Slot 1",
            d: "Buffed weapon.",
            loc: "—",
            up: "N/A",
            tip: "Pre-buff every boss fight.",
          },
          {
            n: "Surge of Hallowed Ground",
            ef: "AoE stagger",
            eq: "Slot 2",
            d: "Crowd control.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        dmg: {
          ps: 650,
          sp: 560,
          bs: 1300,
          n: "Peak endgame. Bleed proc: ~420. Sustained DPS with dual-wield: ~1100.",
        },
      },
      {
        name: "NG+",
        range: "NG+1 and beyond",
        stats: { VIT: 40, END: 40, STR: 50, AGI: 20, RAD: 50, INF: 12 },
        sn: "NG+ — enemies hit harder. Prioritize VIT cap early each cycle. Same loadout.",
        weapons: [],
        armor: [],
        acc: [],
        spells: [],
        dmg: {
          ps: 650,
          sp: 560,
          bs: 1300,
          n: "Same peak damage. Enemy HP/dmg scaled up.",
        },
        ngCycles: [
          {
            label: "NG+1",
            stats: { VIT: 40, END: 40, STR: 50, AGI: 20, RAD: 50, INF: 12 },
            notes:
              "~20% enemy HP increase. Bleed still procs reliably. Focus VIT first. Same loadout performs well.",
          },
          {
            label: "NG+3",
            stats: { VIT: 45, END: 40, STR: 50, AGI: 20, RAD: 50, INF: 12 },
            notes:
              "~50% HP increase. Boss fights take longer — stagger cycles become key. Add Briar Ring if not already equipped.",
          },
          {
            label: "NG+5",
            stats: { VIT: 50, END: 40, STR: 50, AGI: 22, RAD: 50, INF: 14 },
            notes:
              "~90% HP increase. Dual-wield bleed spam remains viable. Consider a secondary bleed weapon in case of resist stacking.",
          },
          {
            label: "NG+7",
            stats: { VIT: 55, END: 40, STR: 50, AGI: 24, RAD: 50, INF: 16 },
            notes:
              "~150% HP increase. True test. Bleed proc per trigger: ~700+. Keep Surge of Hallowed Ground for panic AoE in mob areas.",
          },
        ],
      },
    ],
    sim: [
      {
        label: "Umbral Reaper",
        sub: "Pure INF/RAD bleed",
        icon: "🌑",
        a: "#b370d8",
        cls: "Condemned",
        why: "Similar bleed focus but leans into Inferno stats for umbral-native weapons. Harder to gear but higher ceiling in late game.",
        ph: [
          {
            name: "Early",
            stats: { INF: 18, RAD: 12, END: 20 },
            weapons: ["Elianne the Starved"],
          },
          {
            name: "Mid",
            stats: { INF: 35, RAD: 25, END: 32 },
            weapons: ["Elianne +3", "Ruiner Greatblade"],
          },
          {
            name: "End",
            stats: { INF: 50, RAD: 45, END: 40 },
            weapons: ["Elianne +5", "Pieta's Sword"],
          },
        ],
        key: ["Elianne the Starved", "Ruiner Greatblade", "Umbral Scouring x5"],
        steps: [
          "Choose Condemned class for high INF start",
          "Rush Elianne in Fitzroy's Gorge before leveling further",
          "Prioritize INF to 35, then split RAD/END",
          "Umbral Scouring at +3 for big bleed jump",
          "NG+ — add Pieta's Sword for RAD option vs. umbral-resist bosses",
        ],
      },
    ],
    oth: [
      {
        label: "Faith Hammer",
        sub: "STR/RAD colossal bonk",
        icon: "🔨",
        a: "#e8c05a",
        cls: "Hallowed Knight",
        why: "For players who prefer slow colossal hits over dual-wield spam. RAD stat overlap means you can pivot from Crimson Reaper with minimal respec.",
        ph: [
          {
            name: "Early",
            stats: { STR: 22, RAD: 15, END: 20 },
            weapons: ["Blessed Remembrance"],
          },
          {
            name: "Mid",
            stats: { STR: 38, RAD: 28, END: 35 },
            weapons: ["Blessed Remembrance +3", "Hallowed Ground Hammer"],
          },
          {
            name: "End",
            stats: { STR: 50, RAD: 50, END: 40 },
            weapons: ["Blessed Remembrance +5", "Hallowed Ground Hammer +5"],
          },
        ],
        key: [
          "Blessed Remembrance",
          "Hallowed Ground Hammer",
          "Fulgrite x6",
          "Surge of Hallowed Ground",
        ],
        steps: [
          "Choose Hallowed Knight for high STR/RAD start",
          "Farm Blessed Remembrance from first remembrance boss",
          "Rush STR to 35 for colossal two-hand mode",
          "Fulgrite infusion at +3 for RAD scaling bump",
          "Endgame: Surge of Hallowed Ground for AoE stunlock combo",
        ],
      },
    ],
    ref: [
      {
        n: "Bloody Glory",
        i: "Sword",
        w: 9.4,
        ap: 415,
        st: "Bleed 88",
        ar: "—",
        s: "A/C STR/RAD",
        a: "Umbral",
      },
      {
        n: "Abiding Defender Sword",
        i: "Sword",
        w: 8.6,
        ap: 360,
        st: "Bleed 66",
        ar: "—",
        s: "B/B STR/RAD",
        a: "Fulgrite",
      },
      {
        n: "Crimson Rector Pendant",
        i: "Amulet",
        w: 0.4,
        ap: 0,
        st: "Bleed +15%",
        ar: "—",
        s: "—",
        a: "—",
      },
      {
        n: "Sinner's Ring",
        i: "Ring",
        w: 0.3,
        ap: 0,
        st: "+10% status",
        ar: "—",
        s: "—",
        a: "—",
      },
      {
        n: "Remnant Knight Chestplate",
        i: "Armor",
        w: 12.0,
        ap: 0,
        st: "—",
        ar: "42 Phys",
        s: "—",
        a: "—",
      },
    ],
  },

  // ── LOTF: Wither Reaper ───────────────────────────────────────────────────
  {
    key: "wither-reaper",
    gameKey: "lotf",
    label: "Wither Reaper",
    sub: "Umbral INF/RAD Combo",
    icon: "🌑",
    accent: "#b370d8",
    playstyle:
      "Harnesses the umbral realm's power through Elianne the Starved and Pieta's Holy Sword in tandem. Inferno stats drive the umbral blade while Radiance sustains HP via blessed effects. A deliberate build that alternates between aggressive umbral combos and healing spellcasts.",
    cls: "Condemned",
    caps: ["INF 50", "RAD 50", "END 40"],
    weaponReq: ["INF 20", "RAD 14", "AGI 10"],
    loadouts: null,
    phases: [
      {
        name: "Early Game",
        range: "Levels 1–40",
        stats: { VIT: 14, END: 18, STR: 10, AGI: 10, RAD: 14, INF: 20 },
        sn: "Rush INF to 20 for Elianne requirement. RAD 14 unlocks early blessings.",
        weapons: [
          {
            n: "Elianne the Starved",
            ap: 210,
            wt: 7.8,
            ef: "Umbral Decay 35",
            eq: "Main Hand",
            d: "Core weapon — high INF scaling, unique umbral decay status that ignores some armor.",
            loc: "Fitzroy's Gorge — on a body near the first major umbral tear",
            up: "+1→+5 Deralium Nuggets / Chunks",
            tip: "Pick up immediately. Requires INF 20 — level before exploring deep.",
          },
        ],
        armor: [
          {
            n: "Condemned Rags",
            wt: 6.4,
            eq: "Full Set",
            d: "Starting class armor. Keep for a long time due to light weight.",
            loc: "Starting equipment",
            up: "N/A",
            tip: "Stay light load early — umbral gameplay requires dodge mobility.",
          },
        ],
        acc: [],
        spells: [
          {
            n: "Inferno Surge",
            ef: "Fire projectile, moderate DMG",
            eq: "Spell Slot 1",
            d: "Basic inferno attack spell. Useful at range.",
            loc: "Starting spell for Condemned class",
            up: "N/A",
            tip: "Use for ranged poke in early fights.",
          },
        ],
        dmg: {
          ps: 230,
          sp: 195,
          bs: 460,
          n: "Elianne early. Umbral Decay procs every 5–6 hits for ~160 bonus.",
        },
      },
      {
        name: "Core Weapon",
        range: "Levels 40–60",
        stats: { VIT: 18, END: 25, STR: 10, AGI: 12, RAD: 22, INF: 32 },
        sn: "INF to 32 for major Elianne scaling jump. Acquire Pieta's combo piece.",
        weapons: [
          {
            n: "Elianne the Starved +3",
            ap: 310,
            wt: 7.8,
            ef: "Umbral Decay 55",
            eq: "Main Hand",
            d: "Mid-upgrade. Major jump in INF scaling at +3.",
            loc: "Upgraded at Pieta's Sanctum blacksmith",
            up: "Deralium Chunks × 3",
            tip: "Rush +3 before finishing Fief of the Chill Curse.",
          },
          {
            n: "Pieta's Holy Sword",
            ap: 245,
            wt: 8.2,
            ef: "Radiant Burn 30",
            eq: "Off Hand",
            d: "Radiance-scaling sword that complements INF main-hand. Swap to counter umbral-resistant enemies.",
            loc: "Pieta, She of Blessed Renewal boss drop (first encounter)",
            up: "+1→+3 with Fulgrite",
            tip: "Keep in left hand. Weapon art 'Penitent Surge' applies Radiant Burn.",
          },
        ],
        armor: [
          {
            n: "Pale Butcher Coat",
            wt: 9.6,
            eq: "Chest",
            d: "Good INF-associated armor with +5% umbral damage passive.",
            loc: "Obtained in Revelation Depths after clearing second boss",
            up: "N/A",
            tip: "Strongest mid-game chest for this build.",
          },
        ],
        acc: [
          {
            n: "Sinner's Ring",
            wt: 0.3,
            ef: "+10% status all",
            eq: "Ring 1",
            d: "Amplifies umbral decay build-up.",
            loc: "Forsaken Fen umbral layer",
            up: "N/A",
            tip: "Core accessory — acquire asap.",
          },
        ],
        spells: [
          {
            n: "Umbral Syphon",
            ef: "Drain HP from enemy, restore self",
            eq: "Spell Slot 1",
            d: "Inferno lifesteal spell. Key sustain tool for the build.",
            loc: "Obtained at Fitzroy's Gorge umbral area — speak to Gerlinde",
            up: "N/A",
            tip: "Cast during boss stagger windows for free healing.",
          },
        ],
        dmg: {
          ps: 390,
          sp: 320,
          bs: 780,
          n: "INF/RAD hybrid. Umbral Decay procs every 5 hits: ~230 bonus.",
        },
      },
      {
        name: "Key Accessories",
        range: "Levels 60–80",
        stats: { VIT: 22, END: 32, STR: 10, AGI: 14, RAD: 30, INF: 40 },
        sn: "INF to 40, approaching soft cap. RAD to 30 for tier-2 spells. Hunt accessories.",
        weapons: [
          {
            n: "Elianne +4",
            ap: 365,
            wt: 7.8,
            ef: "Umbral Decay 68",
            eq: "Main Hand",
            d: "One upgrade from max.",
            loc: "—",
            up: "Deralium Shard × 1",
            tip: "Push to +5 when you have Deralium Shards.",
          },
        ],
        armor: [],
        acc: [
          {
            n: "Umbral Eye of the Remnant",
            wt: 0.3,
            ef: "+12% INF damage",
            eq: "Amulet",
            d: "Unique umbral amulet — big INF damage amp.",
            loc: "Reward from clearing Umbral Flowerbed side area in Bramis Castle",
            up: "N/A",
            tip: "Best in slot for this build. Hunt it immediately.",
          },
          {
            n: "Sinner's Ring",
            wt: 0.3,
            ef: "+10% status",
            eq: "Ring 1",
            d: "Core.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
          {
            n: "Crimson Rector Pendant",
            wt: 0.4,
            ef: "Bleed/Status +15%",
            eq: "Ring 2",
            d: "Also boosts umbral decay buildup.",
            loc: "Upper Calrath chest",
            up: "N/A",
            tip: "Stack this with Sinner's Ring for full status amplification.",
          },
        ],
        spells: [
          {
            n: "Radiant Weapon",
            ef: "+25% RAD damage",
            eq: "Slot 2",
            d: "Buff Pieta's sword for anti-umbral encounters.",
            loc: "Purchased from Molhu RAD 35",
            up: "N/A",
            tip: "Swap Elianne to Pieta + this buff vs. umbral-resistant elites.",
          },
        ],
        dmg: {
          ps: 460,
          sp: 380,
          bs: 920,
          n: "INF at 40 — approaching soft cap returns. Umbral Decay proc: ~290.",
        },
      },
      {
        name: "Unlock Spells",
        range: "Levels 80–95",
        stats: { VIT: 26, END: 36, STR: 10, AGI: 16, RAD: 38, INF: 45 },
        sn: "RAD 38 — tier-3 Radiance spells. INF nearing soft cap.",
        weapons: [
          {
            n: "Elianne +5",
            ap: 420,
            wt: 7.8,
            ef: "Umbral Decay 80",
            eq: "Main Hand",
            d: "Max upgrade.",
            loc: "—",
            up: "Complete",
            tip: "Apply Umbral Scouring for final decay amp.",
          },
        ],
        armor: [],
        acc: [],
        spells: [
          {
            n: "Grand Ritual of the Eclipse",
            ef: "Large AoE Radiance + Umbral burst",
            eq: "Slot 1",
            d: "Unique combined spell — rare tier-3 Radiance spell that also deals Umbral damage. Perfect for this hybrid build.",
            loc: "Reward from completing Molhu's quest line at RAD 38",
            up: "N/A",
            tip: "Best spell in the game for INF/RAD builds. Use in every boss fight opener.",
          },
          {
            n: "Umbral Syphon",
            ef: "HP drain + restore",
            eq: "Slot 2",
            d: "Keep for sustain.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        dmg: {
          ps: 520,
          sp: 440,
          bs: 1040,
          n: "Grand Ritual opener: ~600 AoE. Then sustain with Elianne combo strings.",
        },
      },
      {
        name: "Mid-to-Late",
        range: "Levels 95–115",
        stats: { VIT: 30, END: 38, STR: 10, AGI: 18, RAD: 44, INF: 50 },
        sn: "INF hits soft cap. RAD at 44. Final stat consolidation.",
        weapons: [],
        armor: [
          {
            n: "Pale Butcher Set",
            wt: 22.0,
            eq: "Full Set",
            d: "Full set unlocks +8% umbral damage instead of +5% (chest only).",
            loc: "Various: chest from Revelation Depths, rest from umbral vendors",
            up: "N/A",
            tip: "Aim for full set at this stage for the set bonus.",
          },
        ],
        acc: [],
        spells: [],
        dmg: {
          ps: 600,
          sp: 510,
          bs: 1200,
          n: "INF soft cap reached. Grand Ritual: ~750 on opener. Elianne sustained: ~600 DPS.",
        },
      },
      {
        name: "Endgame",
        range: "Levels 115–135",
        stats: { VIT: 38, END: 40, STR: 10, AGI: 20, RAD: 50, INF: 50 },
        sn: "RAD hits soft cap. Full soft cap build. VIT 38 for NG+ survivability.",
        weapons: [
          {
            n: "Elianne +5 (Umbral Scouring)",
            ap: 455,
            wt: 7.8,
            ef: "Umbral Decay 95",
            eq: "Main Hand",
            d: "Peak form with Umbral Scouring applied.",
            loc: "—",
            up: "Complete",
            tip: "Highest Umbral Decay in the game on a fast weapon.",
          },
          {
            n: "Pieta's Holy Sword +5",
            ap: 380,
            wt: 8.2,
            ef: "Radiant Burn 55",
            eq: "Off Hand",
            d: "Max upgraded counter weapon.",
            loc: "—",
            up: "Fulgrite × 5",
            tip: "Swap in for umbral-resistant bosses like Sundered Monarchs.",
          },
        ],
        armor: [
          {
            n: "Pale Butcher Full Set",
            wt: 22.0,
            eq: "Full",
            d: "+8% umbral damage set bonus.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        acc: [
          {
            n: "Umbral Eye of the Remnant",
            wt: 0.3,
            ef: "+12% INF",
            eq: "Amulet",
            d: "BIS.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
          {
            n: "Sinner's Ring",
            wt: 0.3,
            ef: "+10%",
            eq: "Ring 1",
            d: "Core.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
          {
            n: "Crimson Rector Pendant",
            wt: 0.4,
            ef: "+15%",
            eq: "Ring 2",
            d: "Core.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        spells: [
          {
            n: "Grand Ritual of the Eclipse",
            ef: "AoE Radiance+Umbral",
            eq: "Slot 1",
            d: "Opener.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
          {
            n: "Umbral Syphon",
            ef: "HP sustain",
            eq: "Slot 2",
            d: "Sustain.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        dmg: {
          ps: 680,
          sp: 580,
          bs: 1360,
          n: "Full soft caps. Grand Ritual: ~850. Umbral Decay proc: ~480. Pieta counter: ~700.",
        },
      },
      {
        name: "NG+",
        range: "NG+1 and beyond",
        stats: { VIT: 42, END: 40, STR: 10, AGI: 22, RAD: 50, INF: 50 },
        sn: "NG+ — same build. Add VIT. Grand Ritual opener remains king.",
        weapons: [],
        armor: [],
        acc: [],
        spells: [],
        dmg: {
          ps: 680,
          sp: 580,
          bs: 1360,
          n: "Same damage. Enemy scaling increases.",
        },
        ngCycles: [
          {
            label: "NG+1",
            stats: { VIT: 42, END: 40, STR: 10, AGI: 22, RAD: 50, INF: 50 },
            notes:
              "~20% HP increase. Grand Ritual still one-shots trash mobs. Bosses take 2–3 cycles.",
          },
          {
            label: "NG+3",
            stats: { VIT: 48, END: 40, STR: 10, AGI: 22, RAD: 50, INF: 50 },
            notes:
              "~50% HP increase. Umbral Syphon becomes more important for sustain in prolonged fights.",
          },
          {
            label: "NG+5",
            stats: { VIT: 54, END: 40, STR: 12, AGI: 24, RAD: 50, INF: 50 },
            notes:
              "~90% HP increase. Consider Pieta's as primary vs. certain bosses — RAD + Radiant Burn bypasses umbral resist.",
          },
          {
            label: "NG+7",
            stats: { VIT: 60, END: 40, STR: 14, AGI: 26, RAD: 50, INF: 50 },
            notes:
              "~150% HP increase. Grand Ritual opener: ~1800+ AoE. Elianne sustained combo remains the backbone. True endgame test.",
          },
        ],
      },
    ],
    sim: [
      {
        label: "Crimson Reaper",
        sub: "STR/RAD bleed dual-wield",
        icon: "🩸",
        a: "#d64545",
        cls: "Partisan",
        why: "Shares the RAD stat investment. If you like the umbral playstyle but want more straightforward bleed, Crimson Reaper uses the same RAD threshold with STR instead of INF.",
        ph: [
          {
            name: "Early",
            stats: { STR: 18, RAD: 12, END: 20 },
            weapons: ["Hallowed Sword"],
          },
          {
            name: "Mid",
            stats: { STR: 25, RAD: 20, END: 28 },
            weapons: ["Bloody Glory", "Abiding Defender Sword"],
          },
          {
            name: "End",
            stats: { STR: 50, RAD: 50, END: 40 },
            weapons: ["Bloody Glory +5", "Abiding Defender +5"],
          },
        ],
        key: ["Bloody Glory", "Abiding Defender Sword", "Crimson Rector Pendant"],
        steps: [
          "Pick Partisan for STR start",
          "Rush Bloody Glory from Spurned Progeny",
          "STR 50 → RAD 50 soft caps",
          "Dual-wield setup with bleed accessories",
          "Umbral Scouring final bleed amp",
        ],
      },
    ],
    oth: [
      {
        label: "Inferno Pyromancer",
        sub: "INF caster / spell hybrid",
        icon: "🔥",
        a: "#e85a1a",
        cls: "Condemned",
        why: "Full INF caster using the same stat base but pivoting to pure fire spells instead of the weapon-spell hybrid. Loses melee sustain but gains massive single-hit burst.",
        ph: [
          {
            name: "Early",
            stats: { INF: 25, END: 18, VIT: 14 },
            weapons: ["Inferno Catalyst"],
          },
          {
            name: "Mid",
            stats: { INF: 40, RAD: 14, END: 28 },
            weapons: ["Grand Inferno Catalyst", "Elianne backup"],
          },
          {
            name: "End",
            stats: { INF: 50, RAD: 20, END: 38 },
            weapons: ["Grand Inferno Catalyst +5", "Elianne emergency"],
          },
        ],
        key: [
          "Grand Inferno Catalyst",
          "Scalding Surge spell",
          "Grand Conflagration",
          "Umbral Syphon",
        ],
        steps: [
          "Condemned start, dump into INF from level 1",
          "Rush Grand Inferno Catalyst in Revelation Depths",
          "INF 40 — double damage on fire spells",
          "Stack Inferno Quintessence × 6 for scaling bump",
          "Endgame: Grand Conflagration + Scalding Surge combo for 2000+ burst",
        ],
      },
    ],
    ref: [
      {
        n: "Elianne the Starved",
        i: "Sword",
        w: 7.8,
        ap: 455,
        st: "Umbral Decay 95",
        ar: "—",
        s: "A/C INF/RAD",
        a: "Umbral Scouring",
      },
      {
        n: "Pieta's Holy Sword",
        i: "Sword",
        w: 8.2,
        ap: 380,
        st: "Radiant Burn 55",
        ar: "—",
        s: "A/C RAD/AGI",
        a: "Fulgrite",
      },
      {
        n: "Umbral Eye of the Remnant",
        i: "Amulet",
        w: 0.3,
        ap: 0,
        st: "+12% INF",
        ar: "—",
        s: "—",
        a: "—",
      },
      {
        n: "Pale Butcher Set",
        i: "Armor",
        w: 22.0,
        ap: 0,
        st: "—",
        ar: "36 Phys",
        s: "+8% Umbral (set)",
        a: "—",
      },
    ],
  },

  // ── DS1: Sharp Uchigatana ─────────────────────────────────────────────────
  {
    key: "sharp-uchigatana",
    gameKey: "ds1",
    label: "Sharp Uchigatana",
    sub: "DEX Katana — Bleed & Speed",
    icon: "⚡",
    accent: "#e8c05a",
    playstyle:
      "The classic Dark Souls DEX katana build. Fast, bleed-proc heavy, and highly mobile. The Uchigatana's bleed mechanic makes it devastating in PvP and effective in PvE by forcing defensive play on enemies. Wear light armor, dodge constantly, proc bleed, and repeat.",
    cls: "Hunter",
    caps: ["DEX 40", "END 40", "VIT 40"],
    weaponReq: ["DEX 14", "STR 10"],
    loadouts: [
      {
        id: "pvp",
        label: "PvP",
        weaponWt: 5.0,
        endReq: 32,
        armor: "Crimson Set",
        pros: ["Fast roll", "Bleed pressure", "Estus bait"],
        cons: ["Glass cannon", "Low VIT margin"],
      },
      {
        id: "pve",
        label: "PvE",
        weaponWt: 5.0,
        endReq: 30,
        armor: "Shadow Set",
        pros: ["Strong bleed", "Good damage", "Light load"],
        cons: ["Less poise than medium builds"],
      },
    ],
    phases: [
      {
        name: "Early Game",
        range: "SL 1–40",
        stats: { VIT: 16, ATT: 8, END: 20, STR: 10, DEX: 20, RES: 11, INT: 9, FTH: 9 },
        sn: "DEX to 20. END to 20 for stamina. Get the Uchigatana ASAP.",
        weapons: [
          {
            n: "Uchigatana",
            ap: 155,
            wt: 5.0,
            ef: "Bleed 300",
            eq: "Right Hand",
            d: "Core weapon. DEX scaling, innate bleed. Available from game start if you kill Undead Merchant.",
            loc: "Kill the Undead Merchant in Undead Burg (or find it in late game as a drop, but kill the merchant early)",
            up: "+5 → +10 standard path",
            tip: "Buy the Residence Key from the merchant before killing him to keep access to the basement.",
          },
        ],
        armor: [
          {
            n: "Hard Leather Set",
            wt: 14.5,
            eq: "Full Set",
            d: "Light starting armor. Good physical defense relative to weight.",
            loc: "Starting equipment for Hunter class",
            up: "N/A",
            tip: "Switch to Shadow Set when you reach Blighttown.",
          },
        ],
        acc: [],
        spells: [],
        dmg: {
          ps: 170,
          sp: 155,
          bs: 340,
          n: "Standard early. Bleed procs every ~7 hits for ~30% max HP bonus.",
        },
      },
      {
        name: "Core Weapon",
        range: "SL 40–60",
        stats: { VIT: 20, ATT: 10, END: 28, STR: 10, DEX: 30, RES: 11, INT: 9, FTH: 9 },
        sn: "DEX to 30. Push Uchigatana to +10. Acquire Sharp upgrade path.",
        weapons: [
          {
            n: "Uchigatana +10",
            ap: 215,
            wt: 5.0,
            ef: "Bleed 300",
            eq: "Right Hand",
            d: "Standard path maxed. Now ascend via Crystal or stick to +15.",
            loc: "Upgrade at blacksmith (Andre of Astora)",
            up: "+10 requires Very Large Ember + titanite chunks",
            tip: "Get the Very Large Ember from New Londo Ruins early.",
          },
        ],
        armor: [
          {
            n: "Shadow Set",
            wt: 8.2,
            eq: "Full Set",
            d: "Extremely light with decent all-around defense. Best light armor for DEX builds.",
            loc: "Painted World of Ariamis — looted from corpses and mimics in the main courtyard",
            up: "N/A",
            tip: "Farm this early — it stays best-in-slot through endgame.",
          },
        ],
        acc: [
          {
            n: "Ring of Favor and Protection",
            wt: 0.0,
            ef: "+20% HP, +20% Stamina, +5% Equip Load",
            eq: "Ring 1",
            d: "Best ring in the game. Cannot be unequipped without breaking it.",
            loc: "Obtained from killing Knight Lautrec or looting his corpse in Anor Londo",
            up: "N/A",
            tip: "Never take it off once equipped. Plan rings around this.",
          },
        ],
        spells: [],
        dmg: {
          ps: 235,
          sp: 205,
          bs: 470,
          n: "Uchigatana +10. DEX 30 gives B scaling. Bleed proc: ~33% max HP.",
        },
      },
      {
        name: "Key Accessories",
        range: "SL 60–80",
        stats: { VIT: 28, ATT: 10, END: 35, STR: 10, DEX: 36, RES: 11, INT: 9, FTH: 9 },
        sn: "DEX to 36. Collect key rings. Uchigatana to +15.",
        weapons: [
          {
            n: "Uchigatana +15",
            ap: 270,
            wt: 5.0,
            ef: "Bleed 300",
            eq: "Right Hand",
            d: "Max standard path. A scaling at +15 DEX.",
            loc: "—",
            up: "Titanite Slab from Ash Lake or Sif drops",
            tip: "If you want bleed to proc faster, keep standard. If damage only, consider Sharp ascension.",
          },
        ],
        armor: [],
        acc: [
          {
            n: "Ring of Favor and Protection",
            wt: 0.0,
            ef: "+20% HP/STA/Load",
            eq: "Ring 1",
            d: "Core — already equipped.",
            loc: "—",
            up: "N/A",
            tip: "Never remove.",
          },
          {
            n: "Havel's Ring",
            wt: 0.0,
            ef: "+50% Equip Load",
            eq: "Ring 2",
            d: "Allows heavier armor while maintaining fast roll.",
            loc: "Havel's Tower at Darkroot Basin — kill Havel the Rock",
            up: "N/A",
            tip: "Optional — only needed if you want heavier armor. Shadow Set doesn't need it.",
          },
        ],
        spells: [
          {
            n: "Power Within",
            ef: "+40% damage, drains HP",
            eq: "Pyromancy Slot",
            d: "Optional aggressive buff. Drains HP but boosts damage significantly.",
            loc: "Rare drop from Blowdart Sniper in Blighttown (extremely rare) or trade with Snuggly",
            up: "N/A",
            tip: "Use for boss fights only. HP drain is manageable with high VIT.",
          },
        ],
        dmg: {
          ps: 290,
          sp: 255,
          bs: 580,
          n: "Uchigatana +15 with DEX 36. Bleed proc: ~35% max HP. Power Within: +40% window.",
        },
      },
      {
        name: "Unlock Spells",
        range: "SL 80–100",
        stats: { VIT: 35, ATT: 14, END: 40, STR: 10, DEX: 40, RES: 11, INT: 9, FTH: 9 },
        sn: "DEX hits first soft cap (40). END hits soft cap. ATT 14 for pyromancy slot.",
        weapons: [],
        armor: [],
        acc: [],
        spells: [
          {
            n: "Great Combustion",
            ef: "High-damage pyromancy, close range",
            eq: "Pyromancy",
            d: "Highest DPS pyromancy. Used for chip damage in PvE and read punishes in PvP.",
            loc: "Purchased from Laurentius of the Great Swamp at Firelink Shrine",
            up: "Pyromancy Flame +10 for max damage",
            tip: "Clutch in PvP — most players don't expect it from a DEX build.",
          },
          {
            n: "Pyromancy Flame",
            ef: "Catalyst for all pyromancies",
            eq: "Left Hand Catalyst",
            d: "Required for pyromancy. Upgrade to maximize combustion damage.",
            loc: "Given by Laurentius in Depths",
            up: "+15 requires Quelana of Izalith in Blighttown",
            tip: "Get Quelana's upgrades ASAP for max combustion output.",
          },
        ],
        dmg: {
          ps: 310,
          sp: 270,
          bs: 620,
          n: "DEX cap hit. Great Combustion deals ~450 direct hit. Total burst potential: ~1000.",
        },
      },
      {
        name: "Mid-to-Late",
        range: "SL 100–120",
        stats: { VIT: 40, ATT: 14, END: 40, STR: 10, DEX: 40, RES: 11, INT: 9, FTH: 9 },
        sn: "VIT hits first soft cap. Full soft cap core build complete. Fine-tune rings.",
        weapons: [
          {
            n: "Uchigatana +15",
            ap: 270,
            wt: 5.0,
            ef: "Bleed 300",
            eq: "Right Hand",
            d: "Maxed. Consider second Uchigatana in left hand for dual-wield bleed.",
            loc: "—",
            up: "Complete",
            tip: "In PvP: two-hand for extra poise through hits and higher AR.",
          },
        ],
        armor: [
          {
            n: "Shadow Set",
            wt: 8.2,
            eq: "Full Set",
            d: "Maintained throughout. Light load for fast roll.",
            loc: "—",
            up: "N/A",
            tip: "With Ring of FaP + Havel's, you can afford heavier alternatives if desired.",
          },
        ],
        acc: [],
        spells: [],
        dmg: {
          ps: 320,
          sp: 280,
          bs: 640,
          n: "Full core build. Bleed proc: ~36% enemy max HP. Combustion clutch: +450.",
        },
      },
      {
        name: "Endgame",
        range: "SL 120–150",
        stats: { VIT: 50, ATT: 14, END: 40, STR: 10, DEX: 40, RES: 11, INT: 9, FTH: 9 },
        sn: "VIT to 50 for maximum HP. Full endgame optimized loadout.",
        weapons: [
          {
            n: "Uchigatana +15",
            ap: 270,
            wt: 5.0,
            ef: "Bleed 300",
            eq: "Right Hand",
            d: "BIS. Full bleed and DEX scaling.",
            loc: "—",
            up: "Complete",
            tip: "Alternative: Chaos Blade +5 for highest AR katana (costs HP per hit).",
          },
        ],
        armor: [
          {
            n: "Shadow Set",
            wt: 8.2,
            eq: "Full Set",
            d: "BIS for light builds.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        acc: [
          {
            n: "Ring of Favor and Protection",
            wt: 0.0,
            ef: "+20% HP/STA/Load",
            eq: "Ring 1",
            d: "Core.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
          {
            n: "Hornet Ring",
            wt: 0.0,
            ef: "+50% critical hit damage",
            eq: "Ring 2",
            d: "Devastating for backstab and parry builds.",
            loc: "Grove of Sif — found near Sif's grave after defeating him",
            up: "N/A",
            tip: "Pair with riposte cheese for massive burst in PvP.",
          },
        ],
        spells: [
          {
            n: "Great Combustion",
            ef: "+450 flat dmg",
            eq: "Pyromancy",
            d: "Clutch tool.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
          {
            n: "Power Within",
            ef: "+40% damage 30s",
            eq: "Pyromancy 2",
            d: "Boss buff.",
            loc: "—",
            up: "N/A",
            tip: "—",
          },
        ],
        dmg: {
          ps: 340,
          sp: 295,
          bs: 680,
          n: "Endgame DEX build. Bleed proc: ~38% enemy HP. Riposte + Hornet: ~1200. Power Within burst window.",
        },
      },
      {
        name: "NG+",
        range: "NG+1 and beyond",
        stats: { VIT: 50, ATT: 14, END: 40, STR: 10, DEX: 45, RES: 11, INT: 9, FTH: 9 },
        sn: "NG+ — same core. Consider DEX 45–50 for second soft cap returns. Hornet Ring critical synergy.",
        weapons: [],
        armor: [],
        acc: [],
        spells: [],
        dmg: {
          ps: 350,
          sp: 300,
          bs: 700,
          n: "DEX 45 second cap. Marginal gains. Bleed remains strong in NG+ vs. high-HP enemies.",
        },
        ngCycles: [
          {
            label: "NG+1",
            stats: { VIT: 50, ATT: 14, END: 40, STR: 10, DEX: 45, RES: 11, INT: 9, FTH: 9 },
            notes:
              "Enemy HP ~1.5x. Bleed procs more valuable (% based). Same loadout. Add Power Within for boss fights.",
          },
          {
            label: "NG+3",
            stats: { VIT: 50, ATT: 16, END: 40, STR: 10, DEX: 45, RES: 11, INT: 9, FTH: 9 },
            notes:
              "Enemy HP ~2x. Add ATT slot for dual pyromancy. Great Combustion + Power Within combo in boss windows.",
          },
          {
            label: "NG+5",
            stats: { VIT: 50, ATT: 16, END: 40, STR: 12, DEX: 45, RES: 11, INT: 9, FTH: 9 },
            notes:
              "Enemy HP ~3x. Bleed remains relevant — procs every 6–8 hits still dealing 35–40% HP. STR 12 for backup weapon options.",
          },
          {
            label: "NG+7",
            stats: { VIT: 50, ATT: 18, END: 40, STR: 12, DEX: 45, RES: 11, INT: 9, FTH: 9 },
            notes:
              "Enemy HP ~4x. The hardest challenge. Consider Chaos Blade as alternative for max AR. Bleed + combustion burst remains the core loop.",
          },
        ],
      },
    ],
    sim: [
      {
        label: "Chaos Blade Build",
        sub: "Highest AR katana (costs HP)",
        icon: "💀",
        a: "#e85a1a",
        cls: "Wanderer",
        why: "Highest attack rating of any katana in DS1. Costs HP per hit but deals more damage than Uchigatana +15. Same DEX stat investment.",
        ph: [
          {
            name: "Early",
            stats: { DEX: 18, VIT: 18, END: 20 },
            weapons: ["Uchigatana placeholder"],
          },
          {
            name: "Mid",
            stats: { DEX: 35, VIT: 28, END: 32 },
            weapons: ["Great Scythe +10"],
          },
          {
            name: "End",
            stats: { DEX: 40, VIT: 50, END: 40 },
            weapons: ["Chaos Blade +5"],
          },
        ],
        key: ["Chaos Blade", "Red Tearstone Ring", "Ring of FaP"],
        steps: [
          "Rush DEX to 18 for core weapon requirement",
          "Build VIT high — you need HP buffer for Chaos Blade HP drain",
          "Chaos Blade available after beating Seath (boss soul trade)",
          "DEX 40 soft cap then focus VIT/END",
          "Red Tearstone Ring at 20% HP for massive damage boost",
        ],
      },
    ],
    oth: [
      {
        label: "Quality Build",
        sub: "STR/DEX balanced",
        icon: "⚖️",
        a: "#5591c7",
        cls: "Knight",
        why: "Balanced STR/DEX at 27/40 for maximum weapon variety. Uses heavier weapons alongside the Uchigatana for versatility. Good for players who want options in NG+.",
        ph: [
          {
            name: "Early",
            stats: { STR: 16, DEX: 18, END: 20 },
            weapons: ["Longsword +5"],
          },
          {
            name: "Mid",
            stats: { STR: 27, DEX: 30, END: 32 },
            weapons: ["Claymore +10", "Uchigatana +10"],
          },
          {
            name: "End",
            stats: { STR: 27, DEX: 40, END: 40 },
            weapons: ["Claymore +15", "Uchigatana +15"],
          },
        ],
        key: [
          "Claymore",
          "Uchigatana",
          "Elite Knight Armor",
          "Ring of FaP",
          "Havel's Ring",
        ],
        steps: [
          "Knight start for balanced base stats",
          "STR 16 early → pick up Claymore in Undead Parish",
          "STR 27 (two-hand rule: 2/3 req = effective two-hand STR)",
          "DEX 40 soft cap for Uchi DEX scaling",
          "Medium roll target — Elite Knight Set with both rings",
        ],
      },
    ],
    ref: [
      {
        n: "Uchigatana +15",
        i: "Katana",
        w: 5.0,
        ap: 270,
        st: "Bleed 300",
        ar: "—",
        s: "A DEX",
        a: "Standard",
      },
      {
        n: "Ring of Favor and Protection",
        i: "Ring",
        w: 0.0,
        ap: 0,
        st: "+20% HP/STA/Load",
        ar: "—",
        s: "—",
        a: "—",
      },
      {
        n: "Hornet Ring",
        i: "Ring",
        w: 0.0,
        ap: 0,
        st: "+50% crit dmg",
        ar: "—",
        s: "—",
        a: "—",
      },
      {
        n: "Shadow Set",
        i: "Armor",
        w: 8.2,
        ap: 0,
        st: "—",
        ar: "21 Phys",
        s: "—",
        a: "—",
      },
      {
        n: "Great Combustion",
        i: "Pyromancy",
        w: 0.0,
        ap: 450,
        st: "—",
        ar: "—",
        s: "Pyro Flame",
        a: "Fire",
      },
    ],
  },
];
